# Generated by Django 5.1 on 2024-08-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0002_remove_producto_apellidos_remove_producto_nombres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
