# Generated by Django 5.1 on 2024-08-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apl', '0004_producto_cantidad_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_documento', models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extrangería'), ('NIT', 'Número de Identificación Tributaria (NIT)'), ('TI', 'Tarjeta de identidad')], max_length=3)),
            ],
        ),
    ]
